default:
  path: /
  controller: App\Controller\AccueilController::index
  defaults:
    _locale: fr

index:
  path: /{_locale}/
  controller: App\Controller\AccueilController::index
  defaults:
    _locale: fr

boutique:
  path: /{_locale}/boutique/
  controller: App\Controller\BoutiqueController::index

boutiqueChercher:
  path: /{_locale}/boutique/chercher/{produitName}
  controller: App\Controller\BoutiqueController::find

rayon:
  path: /{_locale}/boutique/rayon/{rayonId}
  controller: App\Controller\RayonController::index
  defaults:
    rayonId: 1
  requirements:
    rayonId: '\d+'

panier:
  path: /{_locale}/panier
  controller: App\Controller\PanierController::index

panierAjouter:
  path: /{_locale}/panier/ajouter/{produitId}
  controller: App\Controller\PanierController::add
  defaults:
    produitId: 1
  requirements:
    produitId: '\d+'

panierEnlever:
  path: /{_locale}/panier/enlever/{produitId}
  controller: App\Controller\PanierController::remove
  requirements:
    produitId: '\d+'

panierSupprimer:
  path: /{_locale}/panier/supprimer/{produitId}
  controller: App\Controller\PanierController::delete
  requirements:
    produitId: '\d+'

panierVider:
  path: /{_locale}/panier/vider
  controller: App\Controller\PanierController::clear
  requirements:
    produitId: '\d+'

panierCommander:
  path: /{_locale}/panier/commander
  controller: App\Controller\PanierController::checkout

contact:
  path: /{_locale}/contact
  controller: App\Controller\ContactController::index

compteConnexion:
  path: /{_locale}/compte/connexion
  controller: App\Controller\UserController::new

app_login:
  path: /{_locale}/compte/connexion/login
  controller: App\Controller\SecuriteController::login

compteDetail:
  path: /{_locale}/compte/detail
  controller: App\Controller\CompteController::account

compteCommandes:
  path: /{_locale}/compte/commandes
  controller: App\Controller\CompteController::orders

compteDeconnexion:
  path: /{_locale}/compte/deconnexion
  controller: App\Controller\SecuriteController::logout

changeDevise:
  path: /{_locale}/changeDevise/{devise}
  controller: App\Controller\DeviseController::index

sendEmail:
  path: /{_locale}/compte/sendEmail
  controller: App\Controller\MailerController::commande