index:
  path: /
  controller: App\Controller\AccueilController::index

boutique:
  path: /boutique/
  controller: App\Controller\BoutiqueController::index

rayon:
  path: /boutique/rayon/{rayonId}
  controller: App\Controller\RayonController::index
  defaults:
    rayonId: 1
  requirements:
    rayonId: '\d+'

panier:
  path: /panier
  controller: App\Controller\PanierController::index

panierAjouter:
  path: /panier/ajouter/{produitId}
  controller: App\Controller\PanierController::add
  defaults:
    produitId: 1
  requirements:
    produitId: '\d+'

panierEnlever:
  path: /panier/enlever/{produitId}
  controller: App\Controller\PanierController::remove
  requirements:
    produitId: '\d+'

panierSupprimer:
  path: /panier/supprimer/{produitId}
  controller: App\Controller\PanierController::delete
  requirements:
    produitId: '\d+'

panierVider:
  path: /panier/vider
  controller: App\Controller\PanierController::clear
  requirements:
    produitId: '\d+'

panierCommander:
  path: /panier/commander
  controller: App\Controller\PanierController::checkout

contact:
  path: /contact
  controller: App\Controller\ContactController::index

compteConnexion:
  path: /compte/connexion
  controller: App\Controller\CompteController::connect

compteLogin:
  path: /compte/connexion/login
  controller: App\Controller\CompteController::login

compteDetail:
  path: /compte/detail
  controller: App\Controller\CompteController::account

compteCommandes:
  path: /compte/commandes
  controller: App\Controller\CompteController::orders

compteDeconnexion:
  path: /compte/deconnexion
  controller: App\Controller\CompteController::deconnect
